### ISSUE TITLE
Add support for bs4Dash

### ISSUE THREAD

**Issue by DivadNojnarg** [dreamRs/fresh#1]
☝️

**Comment by DivadNojnarg** [comment]
Could you help me clarify why you say that:

> You cannot mix Bootstrap and AddminLTE variables

What if you want to edit primary, secondary status of shinydashbord cards? (Variables are in Bootstrap in BS4)

**Comment by pvictor** [comment]
AdminLTE CSS includes Bootstrap CSS but map it's own variable to Bootstrap variables, so you just have to specify AdminLTE variables tu generate a theme.

Exemple for boxes in AdminLTE 2 : https://github.com/dreamRs/fresh/blob/8ec555b42e5d0aa6e8723837d09ac5ad6425fb60/inst/assets/adminlte/scss/_boxes.scss#L15
primary is defined with `light-blue`

A peu près the same thing for AdminLTE3, color used for primary stuffs is `$blue`, if you change this variable, all components will be affected.
