### ISSUE TITLE
styling font-color for tab panels (shiny)

### ISSUE THREAD

**Issue by rbcavanaugh** [dreamRs/fresh#10]
Thanks for a great package. Is there anyway to change the font color for tab panels for {shiny}? For example, I would like to change the 'aqua' #18BC9C color in flatly to black. I can do this in a separate CSS file, but it would be nice to generate a single theme from fresh. 

cheers -

**Comment by pvictor** [comment]
The color used in tabs is the color defined for links, yon can change it like this (note that this will apply to all links in your application):

```r

library(shiny)
library(fresh)

ui <- fluidPage(
  use_theme(create_theme(
    bs_vars_global(link_color = "red"),
    bs_vars_pills(active_link_hover_bg = "red")
  )),
  tabsetPanel(
    tabPanel("Plot"),
    tabPanel("Summary")
  ),
  tabsetPanel(
    tabPanel("Plot"),
    tabPanel("Summary"),
    type = "pills"
  )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/4415580/112125911-368d1a80-8bc4-11eb-9409-f205f388980d.png)

Victor

**Comment by rbcavanaugh** [comment]
perfect, thank you!
