### ISSUE TITLE
Clicked button color is not changed even if corresponding status color is changed

### ISSUE THREAD

**Issue by paulimer** [dreamRs/fresh#13]
Hi all,
I have an issue in `bs4dash`, using fresh: if I change the secondary color, using 
```r
bs4dash_status(secondary = "#009982")
```
for instance, the button (the ones with `status = "secondary"` obviously) color on hover looks correct, but not the *clicked* color, which is still a kind of grey, leftover from the initial secondary color I think.

I have searched the `search_vars_bs4dash("button")`, looking for a customizable variable, in vain.

By the way, thanks for this package, it is very useful!

**Comment by paulimer** [comment]
I can confirm it does work with the Github version!

**Comment by pvictor** [comment]
Nice! If it's needed I can push an update on CRAN soon.
